#!/usr/bin/env sh
if ! grep -qE "^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .+" "$COMMIT_MSG_FILE"; then
  echo "Error: Commit message does not follow Conventional Commits format."
  exit 1
fi